// Native Rust application - generated by Briv
// Target: Desktop/Embedded Linux (std)

use std::fmt;

#[derive(Debug, Clone)]
pub struct State {
    pub count: i32,
}

impl Default for State {
    fn default() -> Self {
        Self {
            count: 0,
        }
    }
}

impl State {
    pub fn test_asm(&mut self) -> bool {
        // pre: Eq(Identifier("count"), Integer(0))
        // asm: wfi (clobbers: "x0")
        // Inline asm template:
        // unsafe { asm!("wfi" : : : "x0"); }
        self.count = 1;
        // transaction complete
        // post: Eq(Identifier("count"), Integer(1))
        true
    }

}

fn main() {
    println!("Briv kernel starting\n");
    let mut state = State::default();
    state.test_asm();
    println!("Briv kernel done\n");
}
