// ── Archive Writer (.dbvl) ─────────────────────────────────────────────
// 2026-07-12: Phase 8 — Write compiled Briev modules to .dbvl archives.
// The .dbvl format stores compiled type metadata, intrinsic bindings,
// and function signatures for import by other Briev modules.

use crate::ast::{Definition, PropertyValue, TopLevel};
use std::collections::HashMap;

/// Write a .dbvl archive from a compiled program.
pub fn write_archive(items: &[TopLevel]) -> String {
    let mut out = String::new();
    out.push_str("; .dbvl archive — generated by Briev Compiler\n");
    out.push_str("; Format: tagged lines, one item per line\n\n");

    for item in items {
        match item {
            TopLevel::Definition(defn) => write_definition(defn, &mut out),
            TopLevel::Export(export) => {
                if let TopLevel::Definition(defn) = export.inner.as_ref() {
                    write_export_sig(defn, &mut out);
                }
            }
            TopLevel::Transaction(txn) => write_transaction(txn, &mut out),
            _ => {}
        }
    }

    out
}

/// Write a definition entry to the archive.
fn write_definition(defn: &Definition, out: &mut String) {
    use std::fmt::Write;
    let param_strs: Vec<String> = defn.parameters.iter()
        .map(|(name, ty)| format!("{}:{}", name, format!("{:?}", ty)))
        .collect();
    let ret_str = defn.output_type.as_ref()
        .map(|ot| format!(" -> {:?}", ot))
        .unwrap_or_default();
    writeln!(out, "def {} ({}){}", defn.name, param_strs.join(", "), ret_str).unwrap();
    write_metadata(&defn.metadata, out);
}

/// Write an export signature entry.
fn write_export_sig(defn: &Definition, out: &mut String) {
    use std::fmt::Write;
    let param_strs: Vec<String> = defn.parameters.iter()
        .map(|(name, ty)| format!("{}:{}", name, format!("{:?}", ty)))
        .collect();
    writeln!(out, "export {} ({})", defn.name, param_strs.join(", ")).unwrap();
}

/// Write a transaction entry.
fn write_transaction(txn: &crate::ast::Transaction, out: &mut String) {
    use std::fmt::Write;
    writeln!(out, "txn {} ({})", txn.name,
        txn.parameters.iter()
            .map(|(n, _)| n.clone())
            .collect::<Vec<_>>().join(", "))
        .unwrap();
    write_metadata(&txn.metadata, out);
}

/// Write metadata key/value pairs.
fn write_metadata(metadata: &HashMap<String, PropertyValue>, out: &mut String) {
    for (key, val) in metadata {
        let val_str = match val {
            PropertyValue::Identifier(s) => s.clone(),
            PropertyValue::String(s) => format!("\"{}\"", s),
            PropertyValue::Int(n) => format!("{}", n),
            PropertyValue::Bool(b) => format!("{}", b),
            PropertyValue::Float(f) => format!("{}", f),
            PropertyValue::List(items) => {
                let inner: Vec<String> = items.iter()
                    .map(|v| format!("{:?}", v))
                    .collect();
                format!("[{}]", inner.join(", "))
            }
            // 2026-09-23 (quantities plan): a quantity is written bare.
            PropertyValue::Quantity { .. } => format!("{}", val),
            PropertyValue::HashL => "#L".to_string(),
            PropertyValue::HashR => "#R".to_string(),
            PropertyValue::HashT => "#T".to_string(),
        };
        use std::fmt::Write;
        writeln!(out, "  {} <~ {}", key, val_str).unwrap();
    }
}
