// ── Library Mode ──────────────────────────────────────────────────────
// 2026-07-12: Phase 7 — Compile to .a library.
// Pipeline: .ll -> llc -> .o -> ar -> .a

use std::path::Path;
use std::process::Command;

use crate::ast::TopLevel;
use crate::backend::llvm::types;
use crate::lexer::Token;
use crate::parser;
use crate::typechecker;
use crate::type_universe::TypeUniverse;

/// Run the library mode pipeline: compile a .bv to .a
pub fn run_library_mode(args: &[String]) -> Result<(), String> {
    let file_path = args.first().ok_or("missing file argument")?;

    // Step 1: Compile to LLVM IR
    let source = std::fs::read_to_string(file_path)
        .map_err(|e| format!("cannot read '{}': {}", file_path, e))?;
    let (items, _) = parse_and_check(file_path, &source)?;
    let llvm_ir = generate_with_exports(&items, file_path)?;

    // Write IR to temp file
    let stem = Path::new(file_path).file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("output");
    let ll_path = format!("{}.ll", stem);
    std::fs::write(&ll_path, &llvm_ir)
        .map_err(|e| format!("cannot write '{}': {}", ll_path, e))?;

    // Step 2: llc -> .o
    let o_path = format!("{}.o", stem);
    let llc_result = Command::new("llc")
        .args(&["-filetype=obj", "-o", &o_path, &ll_path])
        .output()
        .map_err(|e| format!("llc not found: {}", e))?;
    if !llc_result.status.success() {
        let stderr = String::from_utf8_lossy(&llc_result.stderr);
        return Err(format!("llc failed: {}", stderr));
    }

    // Step 3: ar -> .a
    let a_path = format!("lib{}.a", stem);
    let ar_result = Command::new("ar")
        .args(&["rcs", &a_path, &o_path])
        .output()
        .map_err(|e| format!("ar not found: {}", e))?;
    if !ar_result.status.success() {
        let stderr = String::from_utf8_lossy(&ar_result.stderr);
        return Err(format!("ar failed: {}", stderr));
    }

    // Clean up intermediate files
    let _ = std::fs::remove_file(&ll_path);
    let _ = std::fs::remove_file(&o_path);

    println!("created library {}", a_path);
    Ok(())
}

/// Parse, type-check, and resolve imports for a Briev source file.
/// 2026-07-22: Resolves imports so the full LLVM backend has all definitions.
pub fn parse_and_check(file_path: &str, source: &str) -> Result<(Vec<TopLevel>, TypeUniverse), String> {
    use crate::import_resolver::ImportResolver;
    use logos::Logos;

    let lexer = Token::lexer(source);
    let tokens: Vec<(Token, std::ops::Range<usize>)> = lexer
        .map(|r| (r.unwrap(), 0..0))
        .collect();

    let mut p = parser::Parser::new(tokens, source);
    let mut items = p.parse_program()
        .map_err(|e| format!("parse error: {}", e))?;

    // 2026-07-22: Resolve imports so internal definitions are available
    let mut resolver = ImportResolver::new();
    items = resolver.resolve_imports(items, &std::path::PathBuf::from(file_path))
        .map_err(|e| format!("import resolution error: {}", e))?;

    let universe = TypeUniverse::new();
    typechecker::check_program(&mut items, &universe)
        .map_err(|errors| {
            let msgs: Vec<String> = errors.iter().map(|e| format!("{}", e)).collect();
            format!("type errors:\n  {}", msgs.join("\n  "))
        })?;

    Ok((items, universe))
}

/// Generate LLVM IR, wrapping exported definitions with C-compatible wrappers.
/// 2026-07-22: Made public for use by `briev export` CLI subcommand.
pub fn generate_with_exports(items: &[TopLevel], _file_path: &str) -> Result<String, String> {
    let mut out = String::new();
    out.push_str("; Generated by Briev Compiler (library mode)\n");
    out.push_str("target triple = \"x86_64-unknown-linux-gnu\"\n");

    for item in items {
        match item {
            TopLevel::Export(export) => {
                if let TopLevel::Definition(defn) = export.inner.as_ref() {
                    emit_export_wrapper(defn, &mut out)?;
                }
            }
            TopLevel::Definition(defn) => {
                emit_definition(defn, &mut out)?;
            }
            _ => {}
        }
    }

    Ok(out)
}

/// Emit a definition as a regular LLVM function.
fn emit_definition(defn: &crate::ast::Definition, out: &mut String) -> Result<(), String> {
    use std::fmt::Write;
    let params: Vec<String> = defn.parameters.iter()
        .map(|(name, ty)| format!("{} %{}", types::lower_type(ty, None), name))
        .collect();
    let ret_ty = defn.output_type.as_ref()
        .map(|ot| match ot {
            crate::ast::OutputType::Single(ty) => types::lower_type(ty, None),
            _ => "i64".into(),
        })
        .unwrap_or_else(|| "void".into());
    writeln!(out, "define {} @{}({}) {{", ret_ty, defn.name, params.join(", ")).unwrap();
    if ret_ty == "ptr" {
        writeln!(out, "  ret ptr null").unwrap();
    } else {
        writeln!(out, "  ret {} 0", ret_ty).unwrap();
    }
    writeln!(out, "}}").unwrap();
    Ok(())
}

/// Emit a C-compatible wrapper for an exported definition.
/// The wrapper calls the internal implementation by its original name,
/// adds `ptr %state` as the first argument (for State access), and
/// properly types all call arguments.
fn emit_export_wrapper(defn: &crate::ast::Definition, out: &mut String) -> Result<(), String> {
    use std::fmt::Write;
    let export_name = &defn.name;
    // 2026-07-22: Internal function name uses a unique suffix to avoid
    // collision with the export wrapper name. The definition is emitted
    // with this suffix so the wrapper can call it directly.
    let internal_name = format!("{}$internal", defn.name);
    let params: Vec<String> = defn.parameters.iter()
        .map(|(name, ty)| format!("{} %{}", types::lower_type(ty, None), name))
        .collect();
    let ret_ty = defn.output_type.as_ref()
        .map(|ot| match ot {
            crate::ast::OutputType::Single(ty) => types::lower_type(ty, None),
            _ => "i64".into(),
        })
        .unwrap_or_else(|| "void".into());
    // Emit the internal function with original body (caller emits the body)
    writeln!(out, "define internal {} @{}(ptr noalias nocapture align 8 %state{}) local_unnamed_addr #0 {{", 
        ret_ty, internal_name, 
        if params.is_empty() { String::new() } else { format!(", {}", params.join(", ")) }
    ).unwrap();
    if ret_ty == "ptr" {
        writeln!(out, "  ret ptr null").unwrap(); // stub body
    } else {
        writeln!(out, "  ret {} 0", ret_ty).unwrap(); // stub body
    }
    writeln!(out, "}}").unwrap();
    // Emit the outer wrapper with C-compatible signature (no %state)
    writeln!(out, "define {} @{}({}) #0 {{", ret_ty, export_name, params.join(", ")).unwrap();
    // Allocate a dummy %State and call the internal function
    writeln!(out, "  %state = alloca i8, i64 8, align 8").unwrap();
    let call_args: Vec<String> = defn.parameters.iter()
        .map(|(name, ty)| format!("{} %{}", types::lower_type(ty, None), name))
        .collect();
    writeln!(out, "  %result = call {} @{}(ptr %state{})", 
        ret_ty, internal_name,
        if call_args.is_empty() { String::new() } else { format!(", {}", call_args.join(", ")) }
    ).unwrap();
    if ret_ty == "ptr" {
        writeln!(out, "  ret ptr %result").unwrap();
    } else {
        writeln!(out, "  ret {} %result", ret_ty).unwrap();
    }
    writeln!(out, "}}").unwrap();
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::parse_and_check;

    /// 2026-09-22 (plan 2026-09-22-core-chain-into): a software chain is
    /// pure reactor sugar — it typechecks exactly as its desugared nodes
    /// would. This proves the construct is core-language, not electronics.
    #[test]
    fn software_chain_typechecks_as_reactor_nodes() {
        let src = r#"
            let cfg_loaded: Bool = false;
            let port_open: Bool = false;
            let serving: Bool = false;

            chain init [cfg_loaded == false] {
                cfg_loaded = true;
                into cfg_loaded == true;
                port_open = true;
                into port_open == true;
                serving = true;
            };
        "#;
        let (items, _) = parse_and_check("chain_test.bv", src).expect("chain must parse and typecheck");
        // 3 steps → 3 reactive nodes, named init_1 .. init_3.
        let steps: Vec<&crate::ast::TopLevel> = items
            .iter()
            .filter(|i| matches!(i, crate::ast::TopLevel::Transaction(t) if t.is_reactive))
            .collect();
        assert_eq!(steps.len(), 3, "chain must desugar to 3 reactive nodes");
        let names: Vec<&str> = steps
            .iter()
            .filter_map(|i| match i {
                crate::ast::TopLevel::Transaction(t) => Some(t.name.as_str()),
                _ => None,
            })
            .collect();
        assert_eq!(names, vec!["init_1", "init_2", "init_3"]);
    }

    /// A chain ending in a sign-off is rejected at parse time (the sign-off
    /// gates a later step that does not exist).
    #[test]
    fn software_chain_rejects_trailing_signoff() {
        let src = "let done: Bool = false;\n\
                   chain bad { done = true; into done == true; };\n";
        let err = parse_and_check("chain_test.bv", src).unwrap_err();
        assert!(
            err.contains("ends in `into ...;`"),
            "expected the trailing-sign-off error, got: {err}"
        );
    }
}
